import Head from "next/head";
import Link from "next/link";
import * as C from "../styles/index";
import { theme } from "../styles/Theme";

import { BsFacebook } from 'react-icons/bs';
import { BsInstagram } from 'react-icons/bs';
import { BsWhatsapp } from 'react-icons/bs';

import Header from "../components/Header";
import { PrimaryButton } from "../components/button/PrimaryButton";
import TitlePitchBar from "../components/title/TitlePitchBar";

export default function Index() {
  return (
    <C.Index>
      <Head>
        <title>DB Tecnologia</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <C.Container>
        <Header />
        
        <C.Pages>
          <C.Home>
            <h1>Aqui você encontra a solução ideal para o seu negócio</h1>

            <div className={"social-media"}>
              <Link href="https://www.facebook.com/" target="_blank">
                <BsFacebook
                  size={40}
                  color="#CCCCCC"
                />
              </Link>
              
              <Link href="https://www.instagram.com/" target="_blank">
                <BsInstagram
                  size={40}
                  color="#CCCCCC"
                />
              </Link>

              <Link href="https://api.whatsapp.com/send?phone=5512988229778" target="_blank">
                <BsWhatsapp
                  size={40}
                  color="#CCCCCC"
                />
              </Link>
            </div>

            <PrimaryButton
              type="button"
              backgroundColor={theme.colors.cheese}
              color="black"
            >
              <Link href="/contato">
                Peça um orçamento
              </Link>
            </PrimaryButton>
          </C.Home>

          <C.PitchBar>
            <div className="container">
              <div className="pitchbar-item">
                <TitlePitchBar>Tecnologias<br/>Mordernas</TitlePitchBar>
                <p>A Qualidade de nossos serviços estão nas tecnologias aplicadas.</p>
              </div>

              <div className="pitchbar-item">
                <TitlePitchBar>Equipe<br/>Qualificada</TitlePitchBar>
                <p>Nossa equipe é altamente treinada e sempre atualizada para trazer o melhor.</p>
              </div>

              <div className="pitchbar-item">
                <TitlePitchBar>Atendimento<br/>Personalizado</TitlePitchBar>
                <p>DB Tecnologia traz um suporte impecável com solução imediata.</p>
              </div>
            </div>
          </C.PitchBar>
        </C.Pages>
      </C.Container>
    </C.Index>
  )
}
