import Head from "next/head";
import * as C from "../styles/index";

import Header from "../components/Header";

export default function Index() {
  return (
    <C.Index>
      <Head>
        <title>DB Tecnologia</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <Header />
        <h1>Aqui você encontra a solução ideal para o seu negócio</h1>
      </div>

    </C.Index>
  )
}
